### ISSUE TITLE
Fix Line Number Error on Restricted Python branch

### ISSUE THREAD

**Issue by ethanchewy** [ethanchewy/PythonBuddy#12]
Here's the branch that needs to be fixed: [https://github.com/ethanchewy/PythonBuddy/tree/restrictedpython](https://github.com/ethanchewy/PythonBuddy/tree/restrictedpython)

Error is pretty simple. The code runs fine and is linted. The line numbers just have to be adjusted correctly. Right now, it displays negative line numbers

To contribute:
- Fork this [branch](https://github.com/ethanchewy/PythonBuddy/tree/restrictedpython). 
- Follow installation [instructions ](https://github.com/ethanchewy/PythonBuddy/blob/master/README.md)for testing: 
- Open a pull request and describe your changes. Please only submit fully functional pull requests. 
- If you have any questions, leave it in this thread.
- **Please only do testing on your own local version of PythonBuddy!!**

_Contributors who are approved for pull requests and make significant contributions will be attributed in the [Contributing.md](https://github.com/ethanchewy/PythonBuddy/blob/master/CONTRIBUTORS.md) file_

**Comment by MarkFilus** [comment]
I'll fix it.

**Comment by MarkFilus** [comment]
ok this works #14

**Comment by ethanchewy** [comment]
@MarkFilus That actually doesn't fix the error at all since it doesn't display the correct number associated with it. 

You would have to run the PythonBuddy app locally and double check to see if the numbers are correct when and error is present.

**Comment by ethanchewy** [comment]
@MarkFilus You didn't fix it. Try running it on your local machine and testing it with various errors first. I left some comments on your pull request.

Thanks for trying though.

**Comment by DirtySoc** [comment]
Can you provide screenshot of issue? I'm running it and don't see the negative line numbers.

![image](https://user-images.githubusercontent.com/33207400/47372464-d4105700-d6b7-11e8-963c-53a948e989c1.png)

**Comment by ethanchewy** [comment]
@DirtySoc Yeah, so this is an old issue that is no longer relevant. 

RestrictedPython is very inflexible and now basically unusable for my use case. 

Here's a better approach to sandboxing Python: https://github.com/ethanchewy/PythonBuddySandboxed
