### ISSUE TITLE
PythonBuddy secretly mines bitcoin without your consent

### ISSUE THREAD

**Issue by Almenon** [ethanchewy/PythonBuddy#22]
Regardless of how you feel about the ethics of that, you should still use the code coinhive provides for mining:

```javascript
<script src="https://authedmine.com/lib/authedmine.min.js"></script>
<script>
	var miner = new CoinHive.Anonymous('YOUR_SITE_KEY', {throttle: 0.3});

	// Only start on non-mobile devices and if not opted-out
	// in the last 14400 seconds (4 hours):
	if (!miner.isMobile() && !miner.didOptOut(14400)) {
		miner.start();
	}
</script>
```
https://coinhive.com/documentation/miner

This is much more reasonable for visitor's CPU's and doesn't drain the battery life of mobile users.  Visitors would have a nicer experience (and electricity bill) without the fan noise that comes with 100% CPU usage.

**Comment by ethanchewy** [comment]
I have taken that out already a month ago on github. Last month, I was testing it out for a few hours on some of my different projects to see how it works. I agree with all of your points that you have stated. 

I didn't realize it was still on the demo server and I will take it out asap. Thank you for pointing this out.
