### ISSUE TITLE
This looks great

### ISSUE THREAD

**Issue by PythonLinks** [ethanchewy/PythonBuddy#23]
Just exactly what I need. 
Thank you so much for all of the hard work. 

Forgive me if I make one comment.  There are really two parts to this. 
One is the core server functionality. 
And the other is the flask app which calls it. 

For those of us who are not using Flask, it would be nice if they were in separate files. 
Then I would not have to import all of flask to use it. 

Otherwise, it looks like lots of hard work has been done by EthanChewy.  
Thank you so much.

**Comment by ethanchewy** [comment]
Hey, thanks for the compliments. 

I'm currently working on a version that leverages Docker containers where every user has its' own container. This would address the issue you are raising. 

Might take a while since I'm quite busy but I'll keep you updated. 

Thanks again!

**Comment by ethanchewy** [comment]
@PythonLinks Here is the dockerized version which creates a docker container for each user session which protects the main server from being hacked with malicious user generated code: https://github.com/ethanchewy/PythonBuddySandboxed
