### ISSUE TITLE
A Demo is worth a thousand words

### ISSUE THREAD

**Issue by PythonLinks** [ethanchewy/PythonBuddy#24]
I am going to try and implement this in my project, but it would be nice to be 
able to see what it looks like.  I can understand that you do not want to run untrusted 
code on your server, but if you could at least show what the editor and syntax checker look like, 
that would be a huge help.

**Comment by PythonLinks** [comment]
On rereading your website, there is the image, but that does not let me play with it. 
I want to actually type in Python Bugs and see what happens. 
Currently my understanding of the system is very abstract. 
I can't reason about it. I have to try it first.

**Comment by ethanchewy** [comment]
That's a good point. I'll probably create a video demo sooner or later. 

Previously, I've hosted Python Buddy with some simple securities but it often gets hacked within a few months, thus why I'm just trying to dockerize each user session. 

This might take a bit of time considering my current part-time job and school work.
