### ISSUE TITLE
Update demo gifs with newest version of PythonBuddy

### ISSUE THREAD

**Issue by ethanchewy** [ethanchewy/PythonBuddy#26]
Problem:
- GIFs in current Readme(https://github.com/ethanchewy/PythonBuddy/blob/master/README.md) show the earliest version of PythonBuddy. 

Goal:
- Produce GIFs of the most current version of PythonBuddy and update them in the Readme

How to do this?
- Follow Readme instructions on installing
- Check out what GIFs are currently displayed in README and take videos of exactly the same functions but wiht updated PythonBuddy
- Load up PythonBuddy in local browser and take screenvideos of site. 
- Convert those clips to GIFs and update readme

**Comment by gurjy0t** [comment]
Hi, I'd like to take this if no one else has yet

**Comment by gurjy0t** [comment]
So while taking the video, I notice a situation in which I fix the error/warning of 'redefined-outer-name', 'undefined-variable', and the written warning goes away. However, the small x symbol next to the line does not. I'm not sure if this is a bug or issue thats known. I didn't see it in the list

**Comment by ethanchewy** [comment]
Yeah, so in the example:
```
def foo(bar, baz):
    pass
foo(42, 42)
```
it is supposed to have warnings. 

I also thought it was weird too. I double checked and copy and pasted it in a seperate python file and manually pylint and still got the same warnings. I think this is an error with Pylint. 

Thank you for noticing that. 

Could you use another example for the gif like example #1 ?

**Comment by gurjy0t** [comment]
Hi, let me clarify. I was trying the example at the very top of read me. The one that defines x outside the scope of foo() and then attempts to modify it. During the process of duplicating that behaviour I saw this:

Define x outside scope -> see red x and errors listed below text box
Define scope inside x -> Error below text box resolve however red x still exists.

I can put up screenshots later if you want. I can ignore it aswell. It just seems like the demo is suppose to show the error/warning go away by moving the `x=10` line into foo().

Lmk if otherwise. Or if you need more info

**Comment by ethanchewy** [comment]
Weird, I don't get the same issue when I replicate. Can you please upload some screenshots? Thanks

**Comment by DirtySoc** [comment]
![image](https://user-images.githubusercontent.com/33207400/47243835-500d5500-d3c1-11e8-91ec-fc8194c44e82.png)

I don't get any sidebar icons at all :( Tried in Firefox and Edge with latest PythonBuddy and Python 3.7.0.

**Comment by ethanchewy** [comment]
@DirtySoc Could you also inspect element and load up the console (https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) and copy any of the error messages and paste it over here?

**Comment by DirtySoc** [comment]
@ethanchewy I setup according to the README. Here are screenshots of "Inspect Element" on the gutter and the console log on a page refresh.

## Inspect Element on Gutter:
![image](https://user-images.githubusercontent.com/33207400/47245408-1e978800-d3c7-11e8-92ab-b3202bd0aa1c.png)

## Console on Refresh
![image](https://user-images.githubusercontent.com/33207400/47245428-3a029300-d3c7-11e8-8fc1-53331fd99701.png)

```PS C:\Users\derek\Documents\repos\PythonBuddy> C:\Users\derek\.envs\PythonBuddy_venv\Scripts\Activate.ps1
(PythonBuddy_venv) PS C:\Users\derek\Documents\repos\PythonBuddy> python -m pip list
Package           Version
----------------- -------
astroid           2.0.4
click             6.7
colorama          0.4.0
dnspython         1.15.0
eventlet          0.24.1
Flask             1.0.2
Flask-SocketIO    3.0.2
greenlet          0.4.15
isort             4.3.4
itsdangerous      0.24
Jinja2            2.10
lazy-object-proxy 1.3.1
MarkupSafe        1.0
mccabe            0.6.1
monotonic         1.5
pip               18.1
pylint            2.1.1
python-engineio   2.2.0
python-socketio   2.0.0
setuptools        39.0.1
six               1.11.0
typed-ast         1.1.0
Werkzeug          0.14.1
wrapt             1.10.11```

**Comment by ethanchewy** [comment]
@DirtySoc Did you create a new virtualenv and is it in Python 3?

If you follow the README, you should get this for `pip list`:
```
(venv) ethanc@ethanc-Q325UAR:~/PythonBuddy$ pip list
Package           Version
----------------- -------
astroid           2.0.4  
click             6.7    
dnspython         1.15.0 
eventlet          0.24.1 
Flask             1.0.2  
Flask-SocketIO    3.0.2  
greenlet          0.4.15 
isort             4.3.4  
itsdangerous      0.24   
Jinja2            2.10   
lazy-object-proxy 1.3.1  
MarkupSafe        1.0    
mccabe            0.6.1  
monotonic         1.5    
pip               18.0   
pylint            2.1.1  
python-engineio   2.2.0  
python-socketio   2.0.0  
setuptools        40.4.1 
six               1.11.0 
typed-ast         1.1.0  
Werkzeug          0.14.1 
wheel             0.31.1 
wrapt             1.10.11
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Also, PythonBuddy has only been tested on Unix systems (Mac, Linux) so that also might be an issues.

**Could you press on the error/warning in the console if any and copy and paste it here? So, play around with the editor by typing stuff and running code and see if there are any errors.  ** 

I'm gonna try to test this out on my Windows system later tonight or tomorrow. 

Thank  you for bringing this up! I'm pretty sure the issue has to do with how temp files are created on Windows vs. Unix systems and maybe the path setup. 

Probably should have tested this on Windows... :P

**Comment by DirtySoc** [comment]
@ethanchewy you are probably right judging by the way the error lines are reported in the app.

## Windows 10 1803 w/ Python3.7:
![image](https://user-images.githubusercontent.com/33207400/47252013-2547ee80-d40b-11e8-9fcc-6ebad2e17c44.png)

## Ubuntu 18.01 w/ Python3.6.6:
![image](https://user-images.githubusercontent.com/33207400/47252254-a99c7080-d40f-11e8-93f7-7f07dbbbf819.png)

**Comment by DirtySoc** [comment]
Here is where the 'HTML1506: Unexpected token.' error goes:
![pythonbuddy-unexpectedtoken](https://user-images.githubusercontent.com/33207400/47252333-fb91c600-d410-11e8-8fa3-7368f05dbc6f.gif)

**Comment by ethanchewy** [comment]
@DirtySoc This is perfect. This gives me a lot to work off of. 

Thank you so much for bringing this up! I'll work on fixing this issue (https://github.com/ethanchewy/PythonBuddy/issues/29) asap

**Comment by ethanchewy** [comment]
@DirtySoc Any updates on creating gifs?

**Comment by ethanchewy** [comment]
https://github.com/ethanchewy/PythonBuddy/commit/5b374159eede85edbfabdfd95613eb66a4895310
