### ISSUE TITLE
Fix PythonBuddy not working in Windows

### ISSUE THREAD

**Issue by ethanchewy** [ethanchewy/PythonBuddy#29]
Line Numbers do not show up correctly when PythonBuddy is running on a Windows system. 

Thank you @DirtySoc for raising this up and providing these screenshots:
Windows 10 1803 w/ Python3.7:
![47252013-2547ee80-d40b-11e8-9fcc-6ebad2e17c44](https://user-images.githubusercontent.com/8660827/47252306-68986200-d3f7-11e8-90f2-865800a87c6c.png)

Ubuntu 18.01 w/ Python3.6.6:
![47252254-a99c7080-d40f-11e8-93f7-7f07dbbbf819](https://user-images.githubusercontent.com/8660827/47252310-7352f700-d3f7-11e8-8ea8-55882ff7ef7b.png)

PythonBuddy was developed for Unix systems so it works on Mac and Ubuntu for example. Unfortunately, the line numbers are not processed correctly in PythonBuddy for Windows. My hunch is that in app.py the data passed in the AJAX calls is formatted differently in Windows systems. Or, there is an issue with creating temp files in Windows system.

**Comment by vladimir-kirillovskiy** [comment]
I'll look at it)

**Comment by vladimir-kirillovskiy** [comment]
I've made a PR, I hope that is how you do it here) 
https://github.com/ethanchewy/PythonBuddy/pull/30
