### ISSUE TITLE
KeyError: 'file_name' by clicking on the Run button

### ISSUE THREAD

**Issue by LeonardoFurtado** [ethanchewy/PythonBuddy#60]
**Describe the bug**
When I start the app, my first test was click on Run button and I've received KeyError: 'file_name'.
Before run the app, i've needed to update werkzeug to the last version cuz with the version in requirements.txt the app cannot be run

**To Reproduce**
1. start application with Flask run (werkzeug updated)
2. Click on Run button
3. open your terminal

**Screenshots**
![xxxx](https://user-images.githubusercontent.com/22118060/96892657-3a274480-1460-11eb-8702-8e6dbc0fc97e.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 // windows 10
 - Browser Firefox

**Additional context**
It happens on my Windows PC and Ubuntu too.

**Comment by ethanchewy** [comment]
Hmmm that's weird - I wasn't able to replicate this on my Linux OS. I'll try testing on Windows in the next few weeks. 

Thanks for bringing this up!

**Comment by ethanchewy** [comment]
lmk if this change helps at all: https://github.com/ethanchewy/PythonBuddy/commit/7889f39acb624e5a146ac7a6052c83106ccf61ef

I think this has to do with socket io not working well in windows.

**Comment by ethanchewy** [comment]
Just double checking, you ran 
`pip install -r requirements.txt`

in your virtualenv before running PythonBuddy, right?

**Comment by LeonardoFurtado** [comment]
> 
> 
> Just double checking, you ran
> `pip install -r requirements.txt`
> 
> in your virtualenv before running PythonBuddy, right?

yep, in both OS I can't run PythonBuddy before update werkzeug, I'll reinstall and try to run whitout update werkzeug and I'll post the error output here.

**Comment by ethanchewy** [comment]
@LeonardoFurtado thank you! I don't develop on Windows but I do have a Windows partition in my laptop so I'll test it out once I can as well.

**Comment by LeonardoFurtado** [comment]
> 
> 
> lmk if this change helps at all: [7889f39](https://github.com/ethanchewy/PythonBuddy/commit/7889f39acb624e5a146ac7a6052c83106ccf61ef)
> 
> I think this has to do with socket io not working well in windows.

Oh, it works, PythonBuddy is throwing a pylint exception in the terminal, but I can still use the editor :). I can't post the exception message now because I don't remember what was written. As soon as I have some time, I'll post it here for you. TY

**Comment by ethanchewy** [comment]
@LeonardoFurtado thank you so much for taking time to dig through this. Appreciate it!

**Comment by ethanchewy** [comment]
@LeonardoFurtado lmk if pulling the most recent changes work! Thanks!

**Comment by ethanchewy** [comment]
Should be resolved.Please let me know if the above recent commits didn't fix it!
