### ISSUE TITLE
Add to and fix the Wiki

### ISSUE THREAD

**Issue by ethanchewy** [ethanchewy/PythonBuddy#9]
Link: [https://github.com/ethanchewy/PythonBuddy/wiki](https://github.com/ethanchewy/PythonBuddy/wiki)

_Contributors who are approved for pull requests and make significant contributions will be attributed in the [Contributing.md](https://github.com/ethanchewy/PythonBuddy/blob/master/CONTRIBUTORS.md) file_

**Comment by anaida07** [comment]
I would like to take this up.
